### ISSUE TITLE
Python: fails at concatenation stage, no pulverize_input_files.txt

### ISSUE THREAD

**Issue by unfa** [sciactive/pulverize#5]
I tried Pulverize Python version today and it rendered the individual chunks fine, but then crashed and left them unconcatenated:

```
(...)
INFO:pulverize:Render processes complete.
Traceback (most recent call last):
  File "./pulverize.py", line 146, in <module>
    join_chunks(args, outdir)
  File "./pulverize.py", line 113, in join_chunks
    with open(file_list, 'w') as fp:
IOError: [Errno 2] No such file or directory: '//Render/pulverize_input_files.txt'
```

Apart from fixing this issue, what can I do right now to concatenate these files to not re-render the whole thing?

**Comment by unfa** [comment]
Ok, so I was able to concatenate the files with  this bash command:

`for f in *.mkv; do echo "file $f" >> list.txt; done; time ffmpeg -f concat -safe 0 -i list.txt -c copy SM57-01.mkv`

I used advice from FFmpeg website: https://trac.ffmpeg.org/wiki/Concatenate
